config/routes.rb
AskAnswer::Application.routes.draw do
  devise_for :users

  root :to => "questions#index"
  get 'tags/:tag', to: 'questions#index', as: :tag
  resources :questions
  devise_for :users, :path => "auth", :path_names => { :sign_in => 'login', :sign_out => 'logout', :password => 'secret', :confirmation => 'verification', :unlock => 'unblock', :registration => 'register', :sign_up => 'cmon_let_me_in' }

end

app/models/question.rb
class Question < ActiveRecord::Base
   attr_accessible :title, :content, :tag_list
   validates_presence_of :title, :content

   acts_as_taggable
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :username
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController 
  before_filter :authenticate_user!, :except => [:index,:show]
  def index
    if params[:tag]
      @questions = Question.tagged_with(params[:tag])
    else
      @questions = Question.all
    end
  end
  
  def show
    @question = Question.find(params[:id])
  end

  def new
    @question = Question.new  
  end

  def create
    @question = Question.new(params[:question])
  #  @question.save!
  #  flash[:notic] = 'Page saved'
  #  redirect_to :action => 'index'
  #  rescue ActiveRecord::RecordInvalid
    #    render  :action => 'new'
    respond_to do |format|
      if @question.save
        format.html  { redirect_to(@question,
                                   :notice => 'question was successfully created.') }
        format.json  { render :json => @question,
                       :status => :created, :location => @question }
      else
        format.html  { render :action => "new" }
        format.json  { render :json => @question.errors,
                       :status => :unprocessable_entity }
      end
    end
  end

  def edit
    @question = Question.find(params[:id])
  end

  def update
    @question = Question.find(params[:id])
#    if @question.save
#      redirect_to(question_path(@question.id), :notice => t("success update"))
#    else
#      render :action => "new"
#    end
    respond_to do |format|
      if @question.update_attributes(params[:question])
        format.html { redirect_to(@question,
                      notic: "Question #{@question.title} was successfully updated") }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
      end
    end
  end

  def destroy
    @question = Question.find(params[:id])
    @question.destroy

    respond_to do |format|
      format.html { redirect_to questions_path }
      format.json { head :no_content}
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(text)
    if text.blank?
      nil
    else
      markdown_render = Redcarpet::Render::HTML.new(:hard_wrap => true, :no_styles => true)
      md = Redcarpet::Markdown.new(markdown_render, :autolink => true, :no_intro_emphasis => true)
      md.render(text).html_safe
    end
  end
#  def markdown(text)
#    GitHub::Markdown.render_gfm(text).to_html.html_safe
#  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AskAnswer</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div id="wrap">
      <div class="container">
        <div id="topbar">
          <ul class="nav nav-tabs">
            <li class="active">
            <a href="#">Questions</a>
            </li>
            <li><a href="#">Tags</a></li>
            <li><a href="#">Users</a></li>
          </ul>
          <div id="user_nav">
              <% if user_signed_in? %>
                <%= current_user.username %>
                <%= link_to "Log out", destroy_user_session_path, :method => :delete %>
              <% else %>
                <%= link_to "Sign up", new_user_registration_path %> or <%= link_to "sign in", new_user_session_path %>
              <% end %>
          </div>
          <div class="askquestion">
              <p>
                <%= link_to "Ask Question", new_question_path, :class => "btn btn-primary" %>
              </p>
          </div>
        </div>
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>

        <div id="main" class="container clear-top">
            <%= yield %>
        </div>
      </div>
      <div id="push"></div>
    </div>
  
    <div id="footbar">
      <div class="container"> 
        <p class="muted credit">
        Created by
        <a href="http://zjhui.me">zjhui</a>
        </p>
      </div>
    </div>
  </body>
</html>

app/views/questions/_form.html.erb
<%= simple_form_for @question do |f| %>
<fieldset>
    <legend><%= @question.new_record? ? t("question.create_topic") : t("questions.edit_topic") %></legend> 
<%= f.input :title, :input_html => { :class => "span6" } %>
<%= f.input :content, :input_html => { :class => "span6" } %>
<%= f.input :tag_list, label: 'Tags (separated by commas)'%>
<%= f.button :submit, :class => 'btn-primary' %>
<%= link_to 'Cancel', @question.id.blank? ? questions_path : question_path(@question), :class => "btn btn-danger" %>
</fieldset>
<% end %>

app/views/questions/edit.html.erb
<div class="content">
    <div class="box">
        <%= render 'form' %>
    </div>
</div>

app/views/questions/index.html.erb
<div id="question">
    <% @questions.each do |question| %>
    <h2><%= link_to question.title, question %></h2>
    <p>
        <%= " created at #{time_ago_in_words(question.created_at)} ago" %>
        <%= link_to 'Edit', edit_question_path(question), :method => :get, :class => "btn btn-mini btn-warning" %>
    </p>
    <p>
        Tags: <%= raw question.tag_list.map { |t| link_to t, tag_path(t) }.join(', ') %>
    </p>
    <% end %>
</div>

app/views/questions/new.html.erb
<div class="content">
    <div class="box">
        <%= render 'form' %>
    </div>
</div>

app/views/questions/show.html.erb
<h2><%= @question.title %></h2>
<p><%= markdown(@question.content) %></p>

<%= link_to 'Destroy', @question, :confirm => 'Are you sure?', method: :delete, :class => "btn btn-danger" %>